export interface HelpArticleSection {
  heading?: string;
  body: string;
}

export interface HelpArticle {
  id: string;
  title: string;
  intro: string;
  sections: HelpArticleSection[];
}

// konten Help Center — statis aja, gak perlu fetch. urutannya ngikutin
// daftar "Popular Topics" di HelpCenterScreen.
export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    intro:
      'STEPI AI is your personal schedule assistant. Here is everything you need to get up and running in a few minutes.',
    sections: [
      {
        heading: '1. Sign in with Google',
        body: 'Create your account with one tap using Google Sign-In. Your account keeps your plans and preferences in sync.',
      },
      {
        heading: '2. Connect Google Calendar',
        body: 'Right after signing in, STEPI asks to connect your Google Calendar. This is required — your events power the home timeline, conflict detection, and smart reminders.',
      },
      {
        heading: '3. Explore the Home screen',
        body: 'Home shows your day as a timeline. Swipe the date strip to move between weeks, tap the month name to open the full calendar, and tap any event to see its details.',
      },
      {
        heading: '4. Add your first event',
        body: 'Tap the + button in the middle of the bottom bar. Give it a title, time, and (ideally) a location — STEPI uses locations to estimate travel time and warn you about traffic.',
      },
      {
        heading: '5. Meet the AI assistant',
        body: 'Open the Chatbot tab and ask things like "add a dentist appointment Friday at 10" or "find my free time this week". You can also talk to STEPI with the voice assistant from the mic button.',
      },
    ],
  },
  {
    id: 'connect-calendar',
    title: 'Connect Calendar',
    intro:
      'STEPI stays in two-way sync with your Google Calendar, so changes here show up there and vice versa.',
    sections: [
      {
        heading: 'Connecting',
        body: 'Go to Profile → Connected Apps → Google Calendar, then choose your Google account and allow calendar access. New accounts are asked to connect right after signing in.',
      },
      {
        heading: 'What gets synced',
        body: 'Events you create, edit, or delete in STEPI are written to your primary Google Calendar — including alerts (reminders). Events created elsewhere appear on your STEPI timeline automatically.',
      },
      {
        heading: 'Life Plan sessions',
        body: 'Study sessions generated by a Life Plan live inside STEPI. They appear on your timeline alongside Google events, and disappear from the calendar when you archive or delete the plan.',
      },
      {
        heading: 'Disconnecting',
        body: 'Profile → Connected Apps → Google Calendar → Disconnect. STEPI stops syncing immediately; nothing is deleted from your Google Calendar.',
      },
    ],
  },
  {
    id: 'how-ai-plan-works',
    title: 'How AI Plan Works',
    intro:
      'Life Plan turns a learning goal into a realistic study schedule that respects the calendar you already have.',
    sections: [
      {
        heading: 'Tell STEPI your goal',
        body: 'From the Life Plan tab, create a plan with your goal, topics, date range, available days, and preferred hours. You can also just describe it to the chatbot in plain language.',
      },
      {
        heading: 'Conflict detection',
        body: 'Before creating sessions, STEPI checks every proposed session against your existing schedule. If something clashes, you choose: skip the conflicting day and extend the plan, or move just that day to a free hour.',
      },
      {
        heading: 'Sessions on your calendar',
        body: 'Each study day becomes a session on your timeline. Progress is tracked automatically — sessions are checked off once their day has passed, no manual ticking needed.',
      },
      {
        heading: 'Managing a plan',
        body: 'Open a plan to see this week\'s sessions, add extra tasks, or view a session in the calendar. Long-press a session to remove it. Archive a plan to clean all of its sessions off your calendar in one go.',
      },
    ],
  },
  {
    id: 'reschedule-events',
    title: 'Reschedule Events',
    intro:
      'Plans change — STEPI gives you a few ways to move things around quickly.',
    sections: [
      {
        heading: 'Edit an event',
        body: 'Tap an event on the timeline, then Edit. You can change the title, time, location, notes, attachments, and alert. Changes sync to Google Calendar.',
      },
      {
        heading: 'Smart adjust',
        body: 'When STEPI detects heavy traffic or bad weather around an event, a banner appears on Home. Tap Adjust to pick an option: leave earlier, push everything later, or move the meeting to a suggested free slot.',
      },
      {
        heading: 'Ask the AI',
        body: 'In the Chatbot, say things like "move my 3pm meeting to tomorrow morning" — STEPI proposes the change and applies it once you confirm.',
      },
      {
        heading: 'Delete an event',
        body: 'Open the event and tap Delete Event at the bottom. Deleting a Life Plan session only removes that one session, not the whole plan.',
      },
    ],
  },
  {
    id: 'manage-notifications',
    title: 'Manage Notifications',
    intro:
      'STEPI reminds you before events so you leave on time — you control how and when.',
    sections: [
      {
        heading: 'Event alerts',
        body: 'When creating or editing an event, choose an alert: at the time of the event, or 5, 15, 30 minutes, 1 hour, even 1 day before. The alert is saved with the event.',
      },
      {
        heading: 'Push notifications',
        body: 'Allow notifications when the app asks (or enable them later in your device Settings). STEPI sends a push notification when an event\'s alert time arrives.',
      },
      {
        heading: 'In-app preferences',
        body: 'Profile → Notifications lets you toggle push notifications, plan updates, and traffic alerts. Marketing notifications are off by default.',
      },
      {
        heading: 'Not receiving reminders?',
        body: 'Check that notifications are allowed in your device Settings, and that the event actually has an alert set (open the event — the Alert row shows its current value).',
      },
    ],
  },
];
