import {
  API_BASE_URL as _API_BASE_URL,
  SUPABASE_URL as _SUPABASE_URL,
  SUPABASE_ANON_KEY as _SUPABASE_ANON_KEY,
  GOOGLE_WEB_CLIENT_ID as _GOOGLE_WEB_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID as _GOOGLE_IOS_CLIENT_ID,
} from '@env';

export const API_BASE_URL = _API_BASE_URL;
export const SUPABASE_URL = _SUPABASE_URL;
export const SUPABASE_ANON_KEY = _SUPABASE_ANON_KEY;
export const GOOGLE_WEB_CLIENT_ID = _GOOGLE_WEB_CLIENT_ID;
export const GOOGLE_IOS_CLIENT_ID = _GOOGLE_IOS_CLIENT_ID;
